<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

class InvoiceRequest extends FormRequest
{
    public function authorize(): bool
    {
        return true;
    }

    protected function prepareForValidation()
    {
        // Filter out empty rows generated by dynamic form templates
        if ($this->has('product')) {
            $this->merge([
                'product' => array_filter((array) $this->product, fn($v) => !empty($v))
            ]);
        }
        
        if ($this->has('lens_category')) {
            $this->merge([
                'lens_category' => array_filter((array) $this->lens_category, fn($v) => !empty($v))
            ]);
        }
    }

    public function rules(): array
    {
        return [
            'client_id' => 'required|exists:clients,id',
            'paper_id' => [
                'nullable',
                Rule::exists('papers', 'id')->where('client_id', $this->input('client_id')),
            ],
            'invoice_number' => 'nullable|string|max:50',
            'order_number' => 'nullable|string|max:50',
            'status' => 'nullable|in:paid,partial,unpaid,canceled,cancelled',
            'invoiced_at' => 'required|date',
            'due_at' => 'nullable|date',
            'amount' => 'nullable|numeric|min:0',
            'notes' => 'nullable|string|max:1000',
            'account_id' => 'nullable|exists:accounts,id',
            'paid' => 'nullable|numeric|min:0',

            // Products
            'product' => 'nullable|array',
            'product.*' => 'nullable|string',
            'quantity' => 'nullable|array',
            'quantity.*' => 'nullable|integer|min:1',
            'price' => 'nullable|array',
            'price.*' => 'nullable|numeric|min:0',

            // Lenses
            'lens_range' => 'nullable|array',
            'lens_range.*' => 'nullable|integer',
            'lens_type' => 'nullable|array',
            'lens_type.*' => 'nullable|integer',
            'lens_category' => 'nullable|array',
            'lens_category.*' => 'nullable|string',
            'lens_quantity' => 'nullable|array',
            'lens_quantity.*' => 'nullable|integer|min:1',
            'lens_price' => 'nullable|array',
            'lens_price.*' => 'nullable|numeric|min:0',
            'lens_eye' => 'nullable|array',
            'lens_eye.*' => 'nullable|in:right,left',
        ];
    }

    public function after(): array
    {
        return [
            function ($validator) {
                $hasProducts = !empty($this->input('product'));
                $hasLenses = !empty($this->input('lens_category'));
                
                if (!$hasProducts && !$hasLenses) {
                    $validator->errors()->add('items', __('Please add at least one product or lens.'));
                }
            }
        ];
    }

    public function messages(): array
    {
        return [
            'client_id.required' => 'Please select a client.',
            'client_id.exists' => 'The selected client does not exist.',
            'invoiced_at.required' => 'Invoice date is required.',
        ];
    }
}
