<x-app-layout>
    <x-dynamic-table
        table-id="lens_types_table"
        :columns="$columns"
        :filters="$filters"
        :create-url="route('admin.lens-types.create')"
        :show-checkbox="false"
    />
</x-app-layout>
